import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";
import USDC_ABI from '../src/abis/usdc_abi.json'
import { TransactionRequest } from '@ethersproject/abstract-provider';

const Home: NextPage = () => {
  const getUnsignedTransaction = (contract: any, functionName: any, args: any) => {
    return contract.interface.functions[functionName].encode(args);
  };

  const test = async () => {
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner()

    const USDC_ADDRESS = '0xeb8f08a975ab53e34d8a0330e0d34de942c95926';

    // Section function signature: https://medium.com/mycrypto/why-do-we-need-transaction-data-39c922930e92
    // This is how `095ea7b3` is generated

    const USDCcontract = new ethers.Contract(USDC_ADDRESS, USDC_ABI, provider.getSigner());

    // Generate unsigned transaction manually
    const manuallyGeneratedTX:TransactionRequest = {
      to: USDC_ADDRESS,
      data:"0x095ea7b3000000000000000000000000eb8f08a975ab53e34d8a0330e0d34de942c959260000000000000000000000000000000000000000000000000000000000000001"
    }

    // Generate unsigned transaction from lib
    const libGeneratedTX:TransactionRequest = await USDCcontract.populateTransaction.approve(USDC_ADDRESS, 1)

    console.log(libGeneratedTX)
    const signedTx = await signer.sendTransaction(libGeneratedTX)

    console.log(signedTx)

    // console.log("TEST:")
    // const response = await USDCcontract.approve(USDC_ADDRESS, 1);
    // console.log(response)

  } 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    <button onClick={test}>
      Test
    </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
